### ISSUE TITLE
Saving image does not preserve colormap

### ISSUE THREAD

**Issue by andriii25** [pthom/immvision#5]
I use `ImmVision::Image()` with a floating point array (the format is CV_32FC1) and apply a colormap. This works wonderfully when I just need to display the image in my application, but the file becomes all black when saving the image using the "Save image" button. 

I presume this is because saving is done via `cv::imwrite()`, which converts unsupported formats to an 8UC format (CV_8UC1 in this case probably), and as my raw values are between 0 and 1, the images become almost completely black. Before looking at the source code and familiarising myself with `imwrite()`, this was kind of unexpected for me, as I thought that the saved file would be the same as the displayed image. I think this behaviour should be noted in the comments at least. 

RGB images in CV_8UC3 format also get saved as if they were in BGR format, I assume this is also because of the behaviour `imwrite()`.  I guess this could be solved by converting images based on the current imageparams before saving. 

A possible workaround for the time being for the latter issue is storing image data in BGR format and saving floating point data in HDR or EXR format for the former which support 64 and 32-bit floating-point input, and applying the colormap in some other tool, but that kind of defeats the point IMO.

**Comment by pthom** [comment]
Hi,

Thanks for reaching out.

> This works wonderfully when I just need to display the image in my application

Thanks for the nice feedback!

> but the file becomes all black when saving the image using the "Save image" button.

When you click on "Save Image", this exports the raw image. As a consequence, if your image is CV_32FC1 or CV_32FC3 for example, you need to select a format that supports is. If you save your image with the ".hdr" extension, it should work.
Your next problem will then be that not many programs can read hdr images.


----

#### Added export colormap image button

When a float (CV_32F or CV_64F) image is detected, I added a button "Export colormap image", which should do want you want. I also added some informative tooltips.

<img width="493" alt="image" src="https://github.com/pthom/immvision/assets/7694091/988ab29d-5ba1-4851-952a-9d3a2f539704">

<img width="441" alt="image" src="https://github.com/pthom/immvision/assets/7694091/853daea4-1dab-4f04-8ab1-f507046c918a">

See related commit: https://github.com/pthom/immvision/commit/a11d7f01161be0c7fdc9d17a24e86876f1251018

---

---

#### Perform RGB2BGR conversion when needed

> RGB images in CV_8UC3 format also get saved as if they were in BGR format, I assume this is also because of the behaviour imwrite(). I guess this could be solved by converting images based on the current imageparams before saving.

this is fixed by https://github.com/pthom/immvision/commit/d57aaedf4835c65789ec1506fc52b8f97179dba5

**Comment by andriii25** [comment]
Hi, 

Thank you so much for such a quick reply and fix!

> When you click on "Save Image", this exports the raw image. As a consequence, if your image is CV_32FC1 or CV_32FC3 for example, you need to select a format that supports is. If you save your image with the ".hdr" extension, it should work.
Your next problem will then be that not many programs can read hdr images.

Yes, this is exactly the problem I have run into. 

Anyway, I've just built everything and tested it, and it all works perfectly. 
Thanks again!
