### ISSUE TITLE
immvison does not work well when reducing the image size

### ISSUE THREAD

**Issue by xiefeihua** [pthom/immvision#7]
![image](https://github.com/pthom/immvision/assets/30398462/7113f5d3-3d0b-4ef9-84cf-c772cf69ba31)
When I shrink the image, there will be a lot of noise, especially when the original image is larger
image_drawing.cpp line 237
```  {
                cv::Mat backgroundWithImage = fnMakeBackground();
                cv::warpAffine(finalImage, backgroundWithImage,
                               ZoomPanTransform::ZoomMatrixToM23(params.ZoomPanMatrix),
                               params.ImageDisplaySize,
                               cv::INTER_LINEAR,
                               cv::BorderTypes::BORDER_TRANSPARENT,
                               cv::Scalar(127, 127, 127, 127)
                );
                finalImage = backgroundWithImage;
            }  
``` 

I modified the source code and resized it first when zooming. The effect is much better, but compared with other image viewing tools, it is still a little weak.
The following is the modified code：
```  
 {
                cv::Mat backgroundWithImage = fnMakeBackground();
                double zoomFactorx = static_cast<double>(params.ZoomPanMatrix(0, 0));
                double zoomFactory = static_cast<double>(params.ZoomPanMatrix(1, 1));
                double xScale = static_cast<double>(params.ImageDisplaySize.width) / (double)finalImage.cols;
                double yScale =  static_cast<double>(params.ImageDisplaySize.height) / (double)finalImage.rows;
                cv::Matx33d tmp = params.ZoomPanMatrix;
                if (zoomFactorx < xScale|| zoomFactory < yScale)
                {
                    cv::Mat resizedImage;
                    cv::resize(finalImage, resizedImage, cv::Size(), zoomFactorx, zoomFactory, cv::INTER_AREA);
                    tmp(0, 0) = 1;
                    tmp(1, 1) = 1;
                    finalImage = resizedImage;
                }
                cv::warpAffine(finalImage, backgroundWithImage,
                               ZoomPanTransform::ZoomMatrixToM23(params.ZoomPanMatrix),
                               params.ImageDisplaySize,
                               cv::INTER_NEAREST,
                               cv::BorderTypes::BORDER_TRANSPARENT,
                               cv::Scalar(127, 127, 127, 127)
                );
                finalImage = backgroundWithImage;
            } 
```  

Picture effect tested after modifying the code：
![image](https://github.com/pthom/immvision/assets/30398462/85459311-7e6f-4400-9852-a0f1002ae2d6)

**Comment by pthom** [comment]
Hello, this is already fixed in the master branch, see [current version of image_drawing.cpp](https://github.com/pthom/immvision/blob/b9791af4b1a42326db89e9f1305013f554a0f450/src/immvision/internal/drawing/image_drawing.cpp#L241-L274).

You are likely experiencing this because I did not release a new version of ImGui Bundle. Release v1.3.0 still uses the older version, which had this issue.

I plan to release a new version of ImGui Bundle in the next weeks. In the meantime you can check out the latest version and compile it from source. Or if you are using Python bindings, you can also download pre-compiled bindings in one of the "Wheels" actions such as this one: https://github.com/pthom/imgui_bundle/actions/runs/9210106845

**Comment by xiefeihua** [comment]
Hi,
Thank you so much for such a quick reply and fix! it does work！
